version: "3.8"

services:
  db:
    image: postgres
    container_name: "${DB_NAME}_postgresql"
    restart: always
    environment:
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: "${DB_NAME}_pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: always

  adminer:
    image: adminer:latest
    container_name: "${DB_NAME}_adminer"
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: nette
    ports:
      - "${ADMINER_PORT}:8080"
    restart: always

volumes:
  db_data:
  pgadmin-data:
